server:
  port: 9080
  max-http-header-size: 10KB


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_db
    username: postgres
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        metadata_builder_contributor: com.example.recipes.config.SqlFunctionsRegistry